### PR TITLE
Fix partial name matching and minister minor kinds

### LINKED ISSUE #33: Fix search entities by Name
Since the search endpoint now allows partial name matches, the code needs to be edited in places where a full match is needed

### LINKED ISSUE #34: Change minister to cabinetMinister and stateMinister

### PR DESCRIPTION
**Pull request by zaeema-n**
This pr
- Fixes search entities such that it now works with the partial name match
- Changes all mentions of minister to cabinetMinister and stateMinister in the CSVs as well as the codebase

This pr closes #33 and closes #34

### CODE REVIEW

File: scripts/link_documents/main.go [hunk 1]
```diff
@@ -14,6 +14,17 @@ import (
...
+func filterByExactName(results []models.SearchResult, name string) []models.SearchResult {
+	var exact []models.SearchResult
+	for _, r := range results {
+		if r.Name == name {
+			exact = append(exact, r)
+		}
+	}
+	return exact
+}
+
```
Comment (ChanukaUOJ) [inline scripts/link_documents/main.go]: Better if you access this through a `Util` pkg so it can reuse. The same function exists in the `entity_operations.go` file as well.

File: api/entity_operations.go
Comment (ChanukaUOJ) [inline api/entity_operations.go]: No need to get the government results again n again inside the loop. Take it once in the top of the loop and access inside the loop to reduce API calls.

Comment (ChanukaUOJ) [inline api/entity_operations.go]: Add `Direction: "INCOMING"`

**Review by ChanukaUOJ — APPROVED** [review]
Initial Comments!

**Review by ChanukaUOJ — APPROVED** [review]
LGTM
